spring.application.name=auth-service

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/employee_task_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=manager
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8081

# JWT Secret
jwt.secret=K7gNU3ke59D1Z3Yv2Xj6M4qW8L0pB5nI7rE9aF1sT4o
jwt.expiration=86400000


# Eureka Client Config
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
