# ===============================
# Server

server.port=8080

# ===============================
# Spring Application
# ===============================
spring.application.name=api-gateway

# ===============================
# Spring Cloud Gateway - Routes
# ===============================


# --- API Routes ---

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/auth/(?<segment>.*), /api/auth/${segment}

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/users/(?<segment>.*), /api/users/${segment}

spring.cloud.gateway.routes[2].id=task-service
spring.cloud.gateway.routes[2].uri=lb://TASK-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/tasks/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/tasks/(?<segment>.*), /api/tasks/${segment}

# ===============================
# Global CORS Configuration
# ===============================
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=false

# ===============================
# JWT Configuration
# ===============================
jwt.secret=K7gNU3ke59D1Z3Yv2Xj6M4qW8L0pB5nI7rE9aF1sT4o

# ===============================
# Logging
# ===============================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}